docker_img_RARE = 'ghcr.io/mrilab-i3m/rare-recon:v1'
#docker_img_RARE = 'rare-recon:cuda12.8'
recon_code_RARE = 'stream_recon_RARE.py'
cp_batchsize_RARE = 1000
yml_petra = 'marge_tyger/petra_art.yml'
denoising_pipeline = 'marge_tyger/pipeline_denoising.sh'
snraware_version = 'Local'  # 'None', 'Local', or 'TEP'
tyger_server = 'https://i3m.tyger.cloud'
#tyger_server = 'ssh://user@92.185.248.57:50022/opt/tyger/api.sock'
