"""General-purpose utility functions shared across MaRGE modules."""

import copy
import os

import bm4d
import numpy as np
import nibabel as nib
from skimage.util import view_as_blocks
import scipy as sp
from datetime import date, datetime
from marge.configs import hw_config as hw

import warnings
import pydicom
from pydicom.errors import InvalidDicomError
from pydicom.dataset import Dataset, FileDataset, FileMetaDataset
from pydicom.sequence import Sequence
from pydicom.tag import Tag
from pydicom.uid import EnhancedMRImageStorage, ExplicitVRLittleEndian, PYDICOM_IMPLEMENTATION_UID, generate_uid

def save_dicom(axes_orientation, n_points, fov, dfov, image, file_path=None, meta_data=None, session=None):
    """
    Save a MaRGE reconstruction as a single Enhanced MR DICOM instance.

    The reconstructed image is stored as a multi-frame Enhanced MR object, with
    one frame per slice. Spatial information is encoded using the Enhanced MR
    Functional Groups, including ImageOrientationPatient, ImagePositionPatient,
    PixelSpacing and SliceThickness.

    The scanner-to-patient coordinate transformation is selected according to
    ``session["study"]``. Known anatomical studies are also used to populate the
    DICOM anatomical region and laterality information. Phantom acquisitions are
    identified as quality-control images.

    Parameters
    ----------
    axes_orientation : array-like of int, shape (3,)
        MaRGE image-axis orientation expressed as::

            [RD, PH, SL]

        The values 0, 1 and 2 refer to the three fixed scanner axes. Their
        anatomical direction in the DICOM LPS coordinate system depends on the
        body-part positioning associated with ``session["study"]``.

    n_points : array-like of int, shape (3,)
        Number of reconstructed points in image coordinates::

            [nRD, nPH, nSL]

        These values must agree with ``image.shape``, which is expected to be
        ``[nSL, nPH, nRD]``.

    fov : array-like of float, shape (3,)
        Field of view expressed in the fixed scanner reference frame.

        The elements correspond to the three scanner axes and are independent of
        ``axes_orientation``.

        Units: cm.

    dfov : array-like of float, shape (3,)
        Displacement of the center of the FOV expressed in the same fixed scanner
        reference frame as ``fov``.

        Units: mm.

    image : numpy.ndarray
        Reconstructed image.

        A 3-D image must have shape::

            [nSL, nPH, nRD]

        A 2-D image with shape ``[nPH, nRD]`` is also accepted and is encoded as
        a single-frame volume.

        Complex-valued images are converted to magnitude before being normalized
        to unsigned 16-bit pixel data.

    file_path : str or path-like
        Path of the Enhanced MR DICOM file to be written.

    meta_data : dict, optional
        Additional DICOM metadata.

        Acquisition-related legacy attributes are extracted when present and
        written into the corresponding Enhanced MR Functional Groups. Supported
        examples include::

            RepetitionTime
            EchoTime
            EffectiveEchoTime
            EchoTrainLength
            FlipAngle

        Spatial, pixel and anatomy attributes generated by this function are
        protected from being overwritten by ``meta_data``.

    session : dict, optional
        MaRGE session information.

        Relevant fields include:

        ``study``
            Anatomical region or type of acquisition. Known anatomical values
            include, for example::

                "foot", "feet", "ankle", "leg", "knee",
                "hand", "wrist", "forearm", "elbow", "head"

            Known anatomical studies are mapped to standardized DICOM/SNOMED
            anatomical-region codes and are also used to select the appropriate
            scanner-to-patient coordinate transformation.

            ``"phantom"`` identifies a phantom/QC acquisition and sets
            ``QualityControlImage = "YES"`` without assigning a human anatomical
            region.

            Other study names may be handled using the default scanner-coordinate
            convention without inventing a standardized anatomical code.

        ``side``
            Laterality of paired anatomical regions. Expected values are
            ``"Left"``, ``"Right"`` or ``"None"``.

            For known paired structures such as the knee, wrist or hand, Left and
            Right are converted to DICOM ``FrameLaterality`` values ``"L"`` and
            ``"R"``.

            For unpaired anatomy such as the head, laterality is encoded as
            ``"U"``. The value is not used to determine the scanner orientation.

        Other session fields are used to populate patient, study, series,
        institution, scanner and software metadata.

    Returns
    -------
    pydicom.dataset.FileDataset
        The Enhanced MR dataset that has been written to ``file_path``.

    Notes
    -----
    ``fov`` and ``dfov`` always remain expressed in the fixed scanner reference
    frame. They must not be reordered according to ``axes_orientation``.

    ``ImageOrientationPatient`` is derived from the directions of the RD and PH
    axes in the DICOM LPS patient coordinate system.

    ``ImagePositionPatient`` is calculated independently for every frame and
    represents the center of voxel ``image[k, 0, 0]``.

    The pixel array itself is not flipped to obtain a desired anatomical
    orientation. Instead, the actual relationship between scanner axes and
    patient anatomy is represented explicitly through the DICOM spatial metadata.
    """

    # Session defaults
    defaults = {
        "institution_name": "Example",
        "scanner_manufacturer": "Example",
        "scanner_name": "Example",
        "scanner_serial_number": "UNKNOWN",
        "software_version": "Example",
        "subject_name": "Name",
        "subject_id": "a",
        "study_id": "a",
        "user": "Example",
        "directory": "",
        "StudyInstanceUID": generate_uid(),
        "subject_birthday": "YY/MM/DD",
        "subject_weight": "kg",
        "subject_height": "cm",
        "content_qualification": "RESEARCH",
        "study": "phantom",
        "side": "None",
        "orientation": "FFS",
    }
    if session is None:
        session = {}
    session = {**defaults, **session, }
    if meta_data is None:
        meta_data = {}

    # Work with our own copy
    meta_data = dict(meta_data)

    # Anatomy
    ANATOMIC_REGION_MAP = {
        "feet": {
            "CodeValue": "56459004",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Foot",
            "BodyPartExamined": "FOOT",
            "paired": True,
        },
        "foot": {
            "CodeValue": "56459004",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Foot",
            "BodyPartExamined": "FOOT",
            "paired": True,
        },
        "ankle": {
            "CodeValue": "70258002",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Ankle joint",
            "BodyPartExamined": "ANKLE",
            "paired": True,
        },
        "leg": {
            "CodeValue": "30021000",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Lower leg",
            "BodyPartExamined": "LOWERLEG",
            "paired": True,
        },
        "knee": {
            "CodeValue": "72696002",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Knee",
            "BodyPartExamined": "KNEE",
            "paired": True,
        },
        "hand": {
            "CodeValue": "85562004",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Hand",
            "BodyPartExamined": "HAND",
            "paired": True,
        },
        "wrist": {
            "CodeValue": "74670003",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Wrist joint",
            "BodyPartExamined": "WRIST",
            "paired": True,
        },
        "forearm": {
            "CodeValue": "14975008",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Forearm",
            "BodyPartExamined": "FOREARM",
            "paired": True,
        },
        "elbow": {
            "CodeValue": "16953009",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Elbow joint",
            "BodyPartExamined": "ELBOW",
            "paired": True,
        },
        "head": {
            "CodeValue": "69536005",
            "CodingSchemeDesignator": "SCT",
            "CodeMeaning": "Head",
            "BodyPartExamined": "HEAD",
            "paired": False,
        },
    }

    # Study
    study = session.get("study")
    if study is None:
        raise ValueError("session['study'] must define the anatomical region.")
    study = str(study).strip().lower()
    if study in ANATOMIC_REGION_MAP:
        anatomic_region = ANATOMIC_REGION_MAP[study]
    elif study == "phantom":
        anatomic_region = None
        frame_laterality = "U"
    else:
        anatomic_region = None
        frame_laterality = "U"
        print(f"WARNING: Unknown study '{study}'. No standardized anatomical region will be encoded.")

    # Laterality
    side = session.get("side")
    if side is None or side=='None':
        side = "none"
    side = str(side).strip().lower()
    if anatomic_region is None:
        frame_laterality = "U"
    elif anatomic_region["paired"]:
        SIDE_MAP = {"left": "L", "l": "L", "right": "R", "r": "R"}
        if side in SIDE_MAP:
            frame_laterality = SIDE_MAP[side]
        else:
            print(f"WARNING: Study '{study}' is a paired anatomical region. session['side'] should be 'Left' or 'Right'.")
            frame_laterality = "U"
    else:
        # Unpaired structure, e.g. head
        frame_laterality = "U"

    # Scanner coordinates -> DICOM patient coordinates
    if study in ["feet", "foot", "ankle", "leg", "knee"]:
        # Lower extremity: FFS
        MARGE_TO_LPS = {
            0: np.array([0.0, 0.0, -1.0]),  # I
            1: np.array([0.0, 1.0, 0.0]),  # P
            2: np.array([1.0, 0.0, 0.0]),  # L
        }
    elif study in ["forearm", "elbow"]:
        # Upper extremity palm points towards scanner +Y
        MARGE_TO_LPS = {
            0: np.array([0.0, 0.0, -1.0]),  # S
            1: np.array([0.0, -1.0, 0.0]),  # A
            2: np.array([1.0, 0.0, 0.0]),  # L
        }
    elif study in ["hand", "wrist"]:
        orientation = session.get("orientation")
        if "FFS" in orientation:  # palm down
            MARGE_TO_LPS = {
                0: np.array([0.0, 0.0, -1.0]),  # I
                1: np.array([0.0, 1.0, 0.0]),  # P
                2: np.array([1.0, 0.0, 0.0]),  # L
            }
        elif "FFP" in orientation:  # palm up
            MARGE_TO_LPS = {
                0: np.array([0.0, 0.0, -1.0]),  # I
                1: np.array([0.0, -1.0, 0.0]),  # P
                2: np.array([-1.0, 0.0, 0.0]),  # L
            }
    elif study == "head" or study == "brain":
        # Head: HFS
        MARGE_TO_LPS = {
            0: np.array([0.0, 0.0, 1.0]),  # S
            1: np.array([0.0, 1.0, 0.0]),  # P
            2: np.array([-1.0, 0.0, 0.0]),  # R
        }
    else:
        MARGE_TO_LPS = {
            0: np.array([0.0, 0.0, -1.0]),  # I
            1: np.array([0.0, 1.0, 0.0]),  # P
            2: np.array([1.0, 0.0, 0.0]),  # L
        }

    # =============================================================================
    # Helper functions
    # =============================================================================

    def _ipl_to_lps(vector):
        """
        Convert a displacement expressed in the fixed MaRGE/scanner
        coordinates [axis0, axis1, axis2] into DICOM LPS coordinates,
        using the anatomical positioning selected for this study.
        """
        vector = np.asarray(vector, dtype=float)

        return (vector[0] * MARGE_TO_LPS[0] + vector[1] * MARGE_TO_LPS[1] + vector[2] * MARGE_TO_LPS[2])

    def _dicom_ds(value):
        """
        Format a value for DICOM attributes with VR = DS.
        """
        return f"{float(value):.10g}"

    def _normalize_to_uint16(image):
        """
        Convert magnitude image to unsigned 16-bit DICOM pixels.

        The complete 0...65535 range is used.
        """
        image = np.abs(np.asarray(image, dtype=np.complex128))
        image = np.asarray(image, dtype=np.float64)

        minimum = np.min(image)
        maximum = np.max(image)

        if maximum > minimum:
            image = ( (image - minimum) / (maximum - minimum) * 65535.0)
        else:
            image = np.zeros_like(image)

        return np.round(image).astype("<u2")

    def _create_code_item(code_value, coding_scheme, code_meaning):
        """
        Create a DICOM coded-sequence item.
        """
        item = Dataset()
        item.CodeValue = str(code_value)
        item.CodingSchemeDesignator = str(coding_scheme)
        item.CodeMeaning = str(code_meaning)

        return item

    # Validate geometry
    axes_orientation = np.asarray(axes_orientation, dtype=int)
    n_points = np.asarray(n_points, dtype=int)
    fov = np.asarray(fov, dtype=float)
    dfov = np.asarray(dfov, dtype=float)

    if (axes_orientation.shape != (3,) or sorted(axes_orientation.tolist()) != [0, 1, 2]):
        raise ValueError("axes_orientation must be a permutation of [0, 1, 2]")
    if n_points.shape != (3,):
        raise ValueError("n_points must contain [nRD, nPH, nSL]")
    if fov.shape != (3,):
        raise ValueError("fov must contain [FOV_I, FOV_P, FOV_L]")
    if dfov.shape != (3,):
        raise ValueError("dfov must contain [dI, dP, dL]")

    # Image
    image = np.abs(np.asarray(image))
    if image.ndim == 2:
        image = image[np.newaxis, :, :]
    if image.ndim != 3:
        raise ValueError("image must have shape [nSL, nPH, nRD]")
    nSl, nPh, nRd = image.shape

    # n_points is expressed as [RD, PH, SL]
    expected_n_points = np.array([nRd, nPh, nSl])

    if not np.array_equal(n_points, expected_n_points):
        raise ValueError(
            "n_points does not agree with image.shape. "
            f"Expected [nRD, nPH, nSL] = "
            f"{expected_n_points.tolist()}, "
            f"received {n_points.tolist()}."
        )

    # Axes
    rd, ph, sl = axes_orientation

    # Direction of increasing image index
    U = MARGE_TO_LPS[rd]   # RD / columns
    V = MARGE_TO_LPS[ph]   # PH / rows
    W = MARGE_TO_LPS[sl]   # SL / frames

    # ImageOrientationPatient: [RD direction, PH direction]
    image_orientation_patient = np.concatenate([U, V])

    # FOV and resolution
    # =========================================================================
    # IMPORTANT:
    #
    # fov and dfov remain in the fixed IPL reference.
    #
    # We DO NOT do:
    #     fov = fov[axes_orientation]
    #     dfov = dfov[axes_orientation]
    #
    # Instead, axes_orientation tells us which element corresponds
    # to RD, PH and SL.
    # =========================================================================

    fov_mm = fov * 10.0
    dRd = fov_mm[rd] / nRd
    dPh = fov_mm[ph] / nPh
    dSl = fov_mm[sl] / nSl

    # FOV center -> DICOM [L, P, S]
    center = _ipl_to_lps(dfov)

    # Normalize image
    image_uint16 = _normalize_to_uint16(image)

    # Extract old-style MR metadata
    # These must no longer simply be written as legacy top-level MR tags.
    # They are used to construct Enhanced MR Functional Groups.
    repetition_time = meta_data.pop("RepetitionTime", None)
    echo_time = meta_data.pop("EffectiveEchoTime", meta_data.pop("EchoTime", None))
    echo_train_length = meta_data.pop("EchoTrainLength", None)
    flip_angle = meta_data.pop("FlipAngle", None)
    imaging_frequency = meta_data.pop("ImagingFrequency", None)

    # UIDs
    sop_instance_uid = generate_uid()
    series_instance_uid = generate_uid()
    study_instance_uid = session.get("StudyInstanceUID")
    if not study_instance_uid:
        study_instance_uid = generate_uid()
    frame_of_reference_uid = generate_uid()

    # File Meta
    file_meta = FileMetaDataset()
    file_meta.MediaStorageSOPClassUID = (EnhancedMRImageStorage)
    file_meta.MediaStorageSOPInstanceUID = (sop_instance_uid)
    file_meta.TransferSyntaxUID = (ExplicitVRLittleEndian)
    file_meta.ImplementationClassUID = (PYDICOM_IMPLEMENTATION_UID)

    # Dataset
    ds = FileDataset(
        filename_or_obj=file_path,
        dataset={},
        file_meta=file_meta,
        preamble=b"\0" * 128,
    )

    # SOP
    ds.SOPClassUID = EnhancedMRImageStorage
    ds.SOPInstanceUID = sop_instance_uid

    # Date / Time
    current_time = datetime.now()
    date = current_time.strftime("%Y%m%d")
    time = current_time.strftime("%H%M%S")
    date_time = current_time.strftime("%Y%m%d%H%M%S")
    ds.InstanceCreationDate = date
    ds.InstanceCreationTime = time
    ds.StudyDate = date
    ds.StudyTime = time
    ds.SeriesDate = date
    ds.SeriesTime = time
    ds.AcquisitionDateTime = date_time

    # Patient
    if session["subject_name"] == "Name":
        ds.PatientName = str(session["subject_id"])
    else:
        ds.PatientName = str(session["subject_name"])
    ds.PatientID = str(session["subject_id"])

    # Type 2: must exist, may be empty
    ds.PatientBirthDate = ""
    ds.PatientSex = ""
    birthday = session.get("subject_birthday")
    if (birthday and birthday != "YY/MM/DD"):
        birthday = (str(birthday).replace("/", "").replace("-", ""))
        if len(birthday) == 8:
            ds.PatientBirthDate = birthday
        else:
            warnings.warn("subject_birthday must resolve to YYYYMMDD")

    # Weight is in kg
    weight = session.get("subject_weight")

    if (weight is not None and weight != "kg"):
        ds.PatientWeight = _dicom_ds(float(weight))

    # DICOM PatientSize is in meters.
    # MaRGE historically stores this session value in cm.
    height = session.get("subject_height")

    if (height is not None and height != "cm"):
        height_m = float(height) / 100.0
        ds.PatientSize = _dicom_ds(height_m)

    # Study
    ds.StudyInstanceUID = study_instance_uid
    ds.StudyID = str(session["study_id"])

    # Type 2 attributes
    ds.AccessionNumber = ""
    ds.ReferringPhysicianName = ""

    # Series
    # DICOM modality is MR, not "MR PORTABLE".
    ds.Modality = "MR"
    ds.SeriesInstanceUID = (series_instance_uid)
    ds.SeriesNumber = get_next_series_number(session["study_id"], os.path.join(session["directory"], "dcm"))
    ds.OperatorsName = str(session["user"])
    ds.AcquisitionNumber = 1

    # Frame of Reference
    ds.FrameOfReferenceUID = (frame_of_reference_uid)
    ds.PositionReferenceIndicator = ""

    # Equipment
    ds.InstitutionName = str(session["institution_name"])
    ds.Manufacturer = str(session["scanner_manufacturer"])
    ds.ManufacturerModelName = str(session["scanner_name"])
    ds.DeviceSerialNumber = str(session["scanner_serial_number"])
    ds.SoftwareVersions = (f"MARGE {session['software_version']}")

    # Preserve MaRGE's ImagingFrequency usage.
    try:
        ds.ImagingFrequency = _dicom_ds(imaging_frequency)
    except (NameError, AttributeError):
        pass

    # Enhanced MR Image
    # This exporter receives an already reconstructed image.
    #
    # DERIVED avoids claiming acquisition-level attributes for which this
    # function does not currently have enough information.
    ds.ImageType = ["DERIVED", "PRIMARY", "OTHER", "NONE"]
    ds.ContentQualification = session.get("content_qualification", "RESEARCH")
    ds.PixelPresentation = "MONOCHROME"
    ds.VolumetricProperties = "VOLUME"
    ds.VolumeBasedCalculationTechnique = ("NONE")
    ds.ComplexImageComponent = "MAGNITUDE"
    ds.AcquisitionContrast = "UNKNOWN"

    # Quality Control / Phantom
    if study == "phantom":
        ds.QualityControlImage = "YES"
    else:
        ds.QualityControlImage = "NO"

    # Image Pixel Module
    ds.Rows = int(nPh)
    ds.Columns = int(nRd)
    ds.NumberOfFrames = str(int(nSl))
    ds.SamplesPerPixel = 1
    ds.PhotometricInterpretation = ("MONOCHROME2")

    # Enhanced MR allows 16-bit MONOCHROME2.
    ds.BitsAllocated = 16
    ds.BitsStored = 16
    ds.HighBit = 15

    # unsigned integer
    ds.PixelRepresentation = 0
    ds.BurnedInAnnotation = "NO"
    ds.LossyImageCompression = "00"
    ds.PresentationLUTShape = "IDENTITY"
    ds.PixelData = image_uint16.tobytes(order="C")

    # Acquisition Context
    ds.AcquisitionContextSequence = Sequence([])

    # Shared Functional Groups
    shared = Dataset()

    # Pixel Measures
    pixel_measures = Dataset()

    # DICOM:
    #   PixelSpacing[0] = row spacing    = PH
    #   PixelSpacing[1] = column spacing = RD

    pixel_measures.PixelSpacing = [_dicom_ds(dPh),_dicom_ds(dRd)]
    pixel_measures.SliceThickness = (_dicom_ds(dSl))
    pixel_measures.SpacingBetweenSlices = (_dicom_ds(dSl))
    shared.PixelMeasuresSequence = Sequence([pixel_measures])

    # Plane Orientation
    plane_orientation = Dataset()
    plane_orientation.ImageOrientationPatient = [_dicom_ds(value) for value in image_orientation_patient]
    shared.PlaneOrientationSequence = Sequence([plane_orientation])

    # Pixel Value Transformation
    pixel_transform = Dataset()
    pixel_transform.RescaleIntercept = "0"
    pixel_transform.RescaleSlope = "1"
    pixel_transform.RescaleType = "US"
    shared.PixelValueTransformationSequence = (Sequence([pixel_transform]))

    # MR Image Frame Type
    frame_type = Dataset()
    frame_type.FrameType = ["DERIVED", "PRIMARY", "OTHER", "NONE"]
    frame_type.PixelPresentation = ("MONOCHROME")
    frame_type.VolumetricProperties = ("VOLUME")
    frame_type.VolumeBasedCalculationTechnique = ("NONE")
    frame_type.ComplexImageComponent = ("MAGNITUDE")
    frame_type.AcquisitionContrast = ("UNKNOWN")
    shared.MRImageFrameTypeSequence = Sequence([frame_type])

    # MR Timing and Related Parameters
    if (repetition_time is not None or echo_train_length is not None or flip_angle is not None):
        timing = Dataset()
        if repetition_time is not None:
            timing.RepetitionTime = _dicom_ds(repetition_time)
        if echo_train_length is not None:
            timing.EchoTrainLength = int(echo_train_length)
        if flip_angle is not None:
            timing.FlipAngle = float(flip_angle)
        shared.MRTimingAndRelatedParametersSequence = (Sequence([timing]))

    # MR Echo
    if echo_time is not None:
        echo = Dataset()
        # EffectiveEchoTime VR = FD, therefore use float, NOT _dicom_ds().
        echo.EffectiveEchoTime = float(echo_time)
        shared.MREchoSequence = Sequence([echo])

    # Frame Anatomy
    if (frame_laterality is not None and anatomic_region is not None):
        anatomy = Dataset()
        anatomy.FrameLaterality = frame_laterality
        code = _create_code_item(anatomic_region["CodeValue"],
                                 anatomic_region["CodingSchemeDesignator"],
                                 anatomic_region["CodeMeaning"])
        anatomy.AnatomicRegionSequence = Sequence([code])
        shared.FrameAnatomySequence = Sequence([anatomy])
        ds.BodyPartExamined = anatomic_region["BodyPartExamined"]
    else:
        warnings.warn(
            "Frame Anatomy has not been encoded. "
            "For strict Enhanced MR conformance, provide "
            "meta_data['FrameLaterality'] and "
            "meta_data['AnatomicRegion']."
        )

    # Frame VOI LUT
    voi = Dataset()
    image_min = int(image_uint16.min())
    image_max = int(image_uint16.max())
    if image_max > image_min:
        window_width = (image_max - image_min)
        window_center = (image_max + image_min) / 2.0
    else:
        window_width = 1
        window_center = image_min
    voi.WindowWidth = _dicom_ds(window_width)
    voi.WindowCenter = _dicom_ds(window_center)
    voi.VOILUTFunction = "LINEAR"
    shared.FrameVOILUTSequence = Sequence([voi])
    ds.SharedFunctionalGroupsSequence = (Sequence([shared]))

    # Multi-frame Dimension Module
    dimension_uid = generate_uid()
    dimension_organization = Dataset()
    dimension_organization.DimensionOrganizationUID = (dimension_uid)
    ds.DimensionOrganizationSequence = Sequence([dimension_organization])

    # This object contains one spatial 3-D stack.
    ds.DimensionOrganizationType = "3D"
    dimension_index = Dataset()
    dimension_index.DimensionOrganizationUID = (dimension_uid)

    # InStackPositionNumber
    dimension_index.DimensionIndexPointer = Tag(0x0020,0x9057)

    # FrameContentSequence
    dimension_index.FunctionalGroupPointer = Tag(0x0020,0x9111)
    dimension_index.DimensionDescriptionLabel = ("Slice position")
    ds.DimensionIndexSequence = Sequence([dimension_index])

    # Per-frame Functional Groups
    per_frame = []
    for k in range(nSl):
        frame = Dataset()

        # Frame Content
        frame_content = Dataset()
        frame_content.StackID = "1"
        frame_content.InStackPositionNumber = (k + 1)
        frame_content.DimensionIndexValues = [k + 1]
        frame.FrameContentSequence = Sequence([frame_content])

        # Image Position Patient
        # ---------------------------------------------------------------------
        # ImagePositionPatient is the CENTER of: image[k, 0, 0]
        #
        # Center of volume: center
        #
        # Position within RD: -(nRd - 1)/2 * dRd * U
        # Position within PH: -(nPh - 1)/2 * dPh * V
        # Position of slice k: +(k - (nSl - 1)/2) * dSl * W
        # ---------------------------------------------------------------------

        ipp = (center - ((nRd - 1) / 2.0) * dRd * U - ((nPh - 1) / 2.0) * dPh * V + (k - (nSl - 1) / 2.0) * dSl * W)
        plane_position = Dataset()
        plane_position.ImagePositionPatient = [_dicom_ds(value) for value in ipp]
        frame.PlanePositionSequence = Sequence([plane_position])
        per_frame.append(frame)

    ds.PerFrameFunctionalGroupsSequence = (Sequence(per_frame))

    # =========================================================================
    # Additional metadata supplied by MaRGE
    # =========================================================================
    #
    # Do NOT allow legacy spatial / pixel attributes to overwrite the
    # Enhanced MR structure generated above.
    #
    # =========================================================================

    protected_tags = {
        "SOPClassUID",
        "SOPInstanceUID",
        "StudyInstanceUID",
        "SeriesInstanceUID",
        "PixelData",
        "Rows",
        "Columns",
        "NumberOfFrames",
        "NumberOfSlices",
        "ImageOrientationPatient",
        "ImagePositionPatient",
        "PixelSpacing",
        "SliceThickness",
        "SpacingBetweenSlices",
        "RepetitionTime",
        "EchoTime",
        "EffectiveEchoTime",
        "EchoTrainLength",
        "WindowWidth",
        "WindowCenter",
        "Modality",
    }

    for keyword, value in meta_data.items():
        if keyword in protected_tags:
            continue
        try:
            setattr(ds, keyword, value)
        except Exception as exc:
            warnings.warn(f"Invalid DICOM metadata: {keyword} -> {exc}")

    # Save
    ds.save_as(file_path, enforce_file_format=True)

    return ds

def fix_image_orientation(image, axes, orientation='FFS', rd_direction=1):
    """
    Adjusts the orientation of a 3D image array to match standard anatomical planes
    (sagittal, coronal, or transversal) and returns the oriented image along with labeling
    and metadata for visualization.

    Args:
        image (np.ndarray): A 3D numpy array representing the image data to be reoriented.
        axes (list[int]): A list of three integers representing the current order of the
                          axes in the image (e.g., [0, 1, 2] for x, y, z).

    Returns:
        output (dict): A dictionary containing the following keys:
            - 'widget': A fixed string "image" or "curve" indicating the type of data for visualization.
            - 'data': The reoriented 3D image array (np.ndarray).
            - 'xLabel': A string representing the label for the x-axis in the visualization.
            - 'yLabel': A string representing the label for the y-axis in the visualization.
            - 'title': A string representing the title of the visualization (e.g., "Sagittal").
        image (np.ndarray): Reoriented 3D image array
        dicom_orientation (list): orientation for dicom file
    """

    # Get axes in strings
    axes_dict = {'x': 0, 'y': 1, 'z': 2}
    axes_keys = list(axes_dict.keys())
    axes_vals = list(axes_dict.values())
    axes_str = ['', '', '']
    n = 0
    for val in axes:
        index = axes_vals.index(val)
        axes_str[n] = axes_keys[index]
        n += 1

    # Create output dictionaries to plot figures
    x_label = "%s axis" % axes_str[1]
    y_label = "%s axis" % axes_str[0]
    title = "Image"
    if axes[2] == 2:  # Sagittal
        title = "Sagittal"
        if axes[0] == 0 and axes[1] == 1:
            x_label = "(-Y) A | PHASE | P (+Y)"
            y_label = "(+X) I | READOUT | S (-X)"
            if rd_direction == -1:
                image = image[:, :, ::-1]
        else:
            image = np.transpose(image, (0, 2, 1))
            x_label = "(-Y) A | READOUT | P (+Y)"
            y_label = "(+X) I | PHASE | S (-X)"
            if rd_direction == -1:
                image = image[:, ::-1, :]
        image_orientation_dicom = [0.0, 1.0, 0.0, 0.0, 0.0, -1.0]
    elif axes[2] == 1:  # Coronal
        title = "Coronal"
        if axes[0] == 0 and axes[1] == 2:
            image = np.flip(image, axis=0)
            x_label = "(-Z) R | PHASE | L (+Z)"
            y_label = "(+X) I | READOUT | S (-X)"
            if rd_direction == -1:
                image = image[:, :, ::-1]
        else:
            image = np.transpose(image, (0, 2, 1))
            image = np.flip(image, axis=0)
            x_label = "(-Z) R | READOUT | L (+Z)"
            y_label = "(+X) I | PHASE | S (-X)"
            if rd_direction == -1:
                image = image[:, ::-1, :]
        image_orientation_dicom = [1.0, 0.0, 0.0, 0.0, 0.0, -1.0]
    elif axes[2] == 0:  # Transversal
        title = "Transversal"
        if axes[0] == 1 and axes[1] == 2:
            image = np.flip(image, axis=0)
            x_label = "(-Z) R | PHASE | L (+Z)"
            y_label = "(+Y) P | READOUT | A (-Y)"
            if rd_direction == -1:
                image = image[:, :, ::-1]
        else:
            image = np.transpose(image, (0, 2, 1))
            image = np.flip(image, axis=0)
            x_label = "(-Z) R | READOUT | L (+Z)"
            y_label = "(+Y) P | PHASE | A (-Y)"
            if rd_direction == -1:
                image = image[:, ::-1, :]
        image_orientation_dicom = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0]

    output = {
        'widget': 'image',
        'data': image,
        'xLabel': x_label,
        'yLabel': y_label,
        'title': title,
    }

    return output, image

def save_nifti(axes_orientation, n_points, fov, dfov, image, file_path):
    axes_orientation = np.array(axes_orientation)
    n_xyz = [0, 0, 0]
    reorder = [0, 0, 0]
    for i, axis in enumerate(axes_orientation):
        n_xyz[axis] = n_points[i]
        reorder[axis] = i
    fov = np.array(fov)  # cm
    dfov = np.array(dfov)  # mm
    resolution = fov / n_xyz * 10  # mm
    image = np.transpose(image, axes=(2, 1, 0))
    image = np.transpose(image, reorder)
    image = np.transpose(image, axes=(2, 1, 0))
    image = image[::-1, ::-1, ::-1]
    image = image / np.max(image)

    orientation = 'FFS'

    # Create afine matrix
    if orientation == 'FFS':
        affine = np.zeros((4, 4))
        affine[0, 0] = resolution[2]
        affine[1, 1] = resolution[1]
        affine[2, 2] = resolution[0]
        affine[0, 3] = dfov[2]
        affine[1, 3] = - dfov[1]
        affine[2, 3] = dfov[0]
        affine[3, 3] = 1
    elif orientation == 'HFS':
        print("Affine matrix not ready.")
    elif orientation == 'FFP':
        print("Affine matrix not ready.")
    elif orientation == 'HFP':
        print("Affine matrix not ready.")

    # Create the NIfTI image
    nifti_img = nib.Nifti1Image(np.abs(image), affine)

    # Save the NIfTI file
    nib.save(nifti_img, file_path)

def get_next_series_number(study_id: str, dicom_dir: str) -> int:
    """
    Finds the next available SeriesNumber for a given StudyID in a directory of DICOM files.

    Parameters
    ----------
    study_id : str
        The StudyID to look for.
    dicom_dir : str
        Path to the directory containing DICOM files.

    Returns
    -------
    int
        The next SeriesNumber (max existing + 1), or 1 if none found.
    """
    if not os.path.isdir(dicom_dir):
        return 1  # No folder, start with 1

    series_numbers = []

    for filename in os.listdir(dicom_dir):
        filepath = os.path.join(dicom_dir, filename)
        try:
            ds = pydicom.dcmread(filepath, stop_before_pixels=True)
            if getattr(ds, "StudyID", None) == study_id:
                series_num = getattr(ds, "SeriesNumber", None)
                if series_num is not None:
                    series_numbers.append(int(series_num))
        except (InvalidDicomError, ValueError, OSError):
            continue  # Skip invalid files

    return max(series_numbers, default=0) + 1

def run_cosbell_filter(sampled, data, cosbell_order):
    """
    Apply the Cosbell filter operation to the k-space data along three directions.

    This method applies the Cosbell filter to the k-space data along the readout ('rd'), phase ('ph'), and slice
    ('sl') directions. It modifies the input k-space data in-place.

    Args:
        sampled (ndarray): The sampled k-space coordinates in a nx3 matrix, where n is the number of points in k-space. The three columns correspond to the readout, phase, and slice directions.
        data (ndarray): The 3D matrix representing the k-space data to be filtered (sl, ph, rd).
        cosbell_order (list): The order of the Cosbell filter for each direction (rd, ph, sl)

    Returns:
        ndarray: The filtered k-space data (sl, ph, rd).
    """
    n_points = data.shape

    # Along readout
    k = np.reshape(sampled[:, 0], n_points)
    kmax = np.max(np.abs(k[:]))
    theta = k / kmax
    data *= (np.cos(theta * (np.pi / 2)) ** cosbell_order[0])

    # Along phase
    k = np.reshape(sampled[:, 1], n_points)
    kmax = np.max(np.abs(k[:]))
    theta = k / kmax
    data *= (np.cos(theta * (np.pi / 2)) ** cosbell_order[1])

    # Along slice
    k = np.reshape(sampled[:, 2], n_points)
    kmax = np.max(np.abs(k[:]))
    theta = k / kmax
    data *= (np.cos(theta * (np.pi / 2)) ** cosbell_order[2])

    return data

def run_bm4d_filter(image_data, std=0):
    """
    Apply the BM4D filter to denoise the image.

    This method retrieves the image data, rescales it, calculates the standard deviation for the BM4D filter,
    applies the BM4D filter to denoise the rescaled image, and rescales the denoised image back to its original
    scale.

    Args:
        image_data (ndarray): The input image data.
        std (float): standard deviation for bm4d. If zero, the standard deviation will be calculated automatically. Default 0

    Returns:
        ndarray: The denoised image.

    """
    # Rescale the image data for processing
    reference = np.max(image_data)
    image_rescaled = image_data / reference * 100

    # Calculate the standard deviation for BM4D filter
    if std==0:
        # Quantize image
        num_bins = 1000
        image_quantized = np.digitize(image_rescaled, bins=np.linspace(0, 1, num_bins + 1)) - 1

        # Divide the image into blocks
        n_multi = (np.array(image_quantized.shape) / 5).astype(int) * 5
        blocks_r = view_as_blocks(image_rescaled[0:n_multi[0], 0:n_multi[1], 0:n_multi[2]], block_shape=(5, 5, 5))

        # Calculate the standard deviation for each block
        block_std_devs = np.std(blocks_r, axis=(3, 4, 5))

        # Calculate the average value for each block
        block_mean = np.mean(blocks_r, axis=(3, 4, 5))

        # Find the indices of the block with the minimum mean
        min_mean_index = np.unravel_index(np.argmin(block_mean), block_mean.shape)

        # Extract the block with the highest entropy from the block_std_devs array
        std = 4 * block_std_devs[min_mean_index]
        print("Standard deviation for BM4D: %0.2f" % std)

    # Create a BM4D profile and set options
    profile = bm4d.BM4DProfile()
    stage_arg = bm4d.BM4DStages.ALL_STAGES
    blockmatches = (False, False)

    # Apply the BM4D filter to the rescaled image
    denoised_rescaled = bm4d.bm4d(image_rescaled, sigma_psd=std, profile=profile, stage_arg=stage_arg,
                                  blockmatches=blockmatches)

    # Rescale the denoised image back to its original dimensions
    denoised_image = denoised_rescaled / 100 * reference

    return denoised_image

def run_dfft(image):
    """
    Perform direct FFT reconstruction.

    This method performs the direct Fourier transform to obtain the k-space data from an image in the spatial
    domain.

    Args:
        image (ndarray): The image in the spatial domain (sl, ph, rd).

    Returns:
        ndarray: The k-space data.

    """
    k_space = np.fft.fftshift(np.fft.fftn(np.fft.ifftshift(image)))
    return k_space

def run_ifft(k_space):
    """
    Perform inverse FFT reconstruction.

    This method performs the inverse Fourier transform to reconstruct the image in the spatial domain from k-space
    data.

    Args:
        k_space (ndarray): The k-space data (sl, ph, rd).

    Returns:
        ndarray: The reconstructed image in the spatial domain.

    """
    image = np.fft.ifftshift(np.fft.ifftn(np.fft.fftshift(k_space)))
    return image

def run_zero_padding(k_space, new_size):
    """
    Perform zero-padding on the given k-space data.

    This function retrieves the desired zero-padding dimensions from the user input,
    creates a new k-space matrix with the specified size filled with zeros, and places
    the original k-space data at the center of the new matrix. It ensures that the
    k-space is properly centered even if the new dimensions are larger or smaller
    than the original.

    Parameters:
    -----------
    k_space : np.ndarray
        A 3D complex-valued NumPy array representing the original k-space data.
    new_size: list
        A list with the new matrix size (rd, ph, sli)

    Returns:
    --------
    np.ndarray
        A 3D complex-valued NumPy array containing the new k-space data.

    Notes:
    ------
    - The function calculates the appropriate offsets to center the original k-space
      within the new zero-padded matrix.
    - If the new matrix size is smaller in any dimension, it crops the k-space accordingly.
    """
    # Get the k_space shape
    shape_0 = k_space.shape

    # Determine the new shape after zero-padding
    shape_1 = new_size

    # Create an image matrix filled with zeros
    image_matrix = np.zeros(shape_1, dtype=complex)

    # Calculate the centering offsets for each dimension
    offset_0 = (shape_1[0] - shape_0[0]) // 2
    offset_1 = (shape_1[1] - shape_0[1]) // 2
    offset_2 = (shape_1[2] - shape_0[2]) // 2

    # Calculate the start and end indices to center the k_space within the new image_matrix
    new_start_0 = offset_0 if offset_0 >= 0 else 0
    new_start_1 = offset_1 if offset_1 >= 0 else 0
    new_start_2 = offset_2 if offset_2 >= 0 else 0
    new_end_0 = new_start_0 + shape_0[0] if offset_0 > 0 else shape_1[0]
    new_end_1 = new_start_1 + shape_0[1] if offset_1 > 0 else shape_1[1]
    new_end_2 = new_start_2 + shape_0[2] if offset_2 > 0 else shape_1[2]

    # Calculate the start and end indices of old matrix
    old_start_0 = 0 if offset_0 >= 0 else -offset_0
    old_start_1 = 0 if offset_1 >= 0 else -offset_1
    old_start_2 = 0 if offset_2 >= 0 else -offset_2
    old_end_0 = shape_0[0] if offset_0 >= 0 else old_start_0 + shape_1[0]
    old_end_1 = shape_0[1] if offset_1 >= 0 else old_start_1 + shape_1[1]
    old_end_2 = shape_0[2] if offset_2 >= 0 else old_start_2 + shape_1[2]

    # Copy the k_space into the image_matrix at the center
    image_matrix[new_start_0:new_end_0, new_start_1:new_end_1, new_start_2:new_end_2] = k_space[
                                                                                        old_start_0:old_end_0,
                                                                                        old_start_1:old_end_1,
                                                                                        old_start_2:old_end_2
                                                                                        ]

    return image_matrix

def hanning_filter(kSpace, mm, nb_point):
    """
    Apply a Hanning filter to the k-space data.

    Args:
        kSpace (ndarray): K-space data.
        n (int): Number of zero-filled points in k-space.
        m (int): Number of acquired points in k-space.
        nb_point (int): Number of points before m+n where reconstruction begins to go to zero.

    Returns:
        ndarray: K-space data with the Hanning filter applied.
    """
    kSpace_hanning = np.copy(kSpace)
    kSpace_hanning[mm[0]::, :, :] = 0.0
    kSpace_hanning[:, mm[1]::, :] = 0.0
    kSpace_hanning[:, :, mm[2]::] = 0.0

    # Calculate the Hanning window
    hanning_window = np.hanning(nb_point * 2)
    hanning_window = hanning_window[int(len(hanning_window)/2)::]

    if not mm[0] == np.size(kSpace, 0):
        for ii in range(nb_point):
            kSpace_hanning[mm[0]-nb_point+ii+1, :, :] *= hanning_window[ii]
    if not mm[1] == np.size(kSpace, 1):
        for ii in range(nb_point):
            kSpace_hanning[:, mm[1]-nb_point+ii+1, :] *= hanning_window[ii]
    if not mm[2] == np.size(kSpace, 2):
        for ii in range(nb_point):
            kSpace_hanning[:, :, mm[2]-nb_point+ii+1] *= hanning_window[ii]

    return kSpace_hanning

def run_pocs_reconstruction(n_points, factors, k_space_ref, test=False):
    """
    Perform POCS reconstruction.

    Retrieves the number of points before m+n where reconstruction begins to go to zero.
    Retrieves the correlation threshold for stopping the iterations.
    Computes the partial image and full image for POCS reconstruction.
    Applies the iterative reconstruction with phase correction.
    Updates the main matrix of the image view widget with the interpolated image.
    Adds the "POCS" operation to the history widget and updates the history dictionary and operations history.
    """
    print("Running POCS...")
    def getCenterKSpace(k_space, m_vec):
        """
        Extract the central region of a 3D k-space array, zeroing out the periphery.

        Args:
            k_space (np.ndarray): 3D complex k-space array with shape (sl, ph, rd).
            m_vec (np.ndarray): Half-widths of the central region to keep along each axis.

        Returns:
            np.ndarray: Array of same shape as k_space, with only the central
                [n//2 - m : n//2 + m] region preserved; all other values are zero.
        """
        # fix n_vec
        output = np.zeros(np.shape(k_space), dtype=complex)
        n_vec = np.array(np.shape(k_space))

        # fill with zeros
        idx0 = n_vec // 2 - m_vec
        idx1 = n_vec // 2 + m_vec
        output[idx0[0]:idx1[0], idx0[1]:idx1[1], idx0[2]:idx1[2]] = \
            k_space[idx0[0]:idx1[0], idx0[1]:idx1[1], idx0[2]:idx1[2]]

        return output

    # Get n and m
    factors = [float(num) for num in factors]
    mm = np.array([int(num) for num in (n_points * factors)])
    m = np.array([int(num) for num in (n_points * factors - n_points / 2)])

    # Get the reference image
    img_ref = np.abs(run_ifft(k_space_ref))

    if test:
        n_sl, n_ph, n_rd = np.shape(img_ref)
        plt.figure()
        plt.imshow(img_ref[n_sl // 2, :, :], cmap="gray")
        plt.title("Reference image")

    # Create a copy with the center of k-space
    k_space_center = getCenterKSpace(k_space_ref, m)

    # Number of points before m+n where we begin to go to zero
    nb_point = 2

    # Set the correlation threshold for stopping the iterations
    threshold = 1e-6

    # Get image phase
    img_center = run_ifft(k_space_center)
    phase = img_center / abs(img_center)
    if test:
        plt.figure()
        plt.imshow(np.abs(img_center[n_sl // 2, :, :]), cmap='gray')
        plt.title("Center image")

    # Generate zero padding image for comparison
    k_space_zp = np.zeros_like(k_space_ref, dtype=complex)
    k_space_zp[0:mm[0], 0:mm[1], 0:mm[2]] = k_space_ref[0:mm[0], 0:mm[1], 0:mm[2]]
    img_zp = np.abs(run_ifft(k_space_zp))
    if test:
        plt.figure()
        plt.imshow(np.abs(img_zp[n_sl // 2, :, :]), cmap='gray')
        plt.title("ZP")

    # Generate the corresponding image with the Hanning filter
    k_space_hanning = hanning_filter(k_space_ref, mm, nb_point)
    img_hanning = run_ifft(k_space_hanning)

    num_iterations = 0  # Initialize the iteration counter
    img_reconstructed = [img_hanning]
    while True:
        # Iterative reconstruction
        img_iterative = np.abs(img_reconstructed[-1]) * phase
        k_space_new = run_dfft(img_iterative)

        # Apply constraint: Keep the region of k-space from n+m onwards and restore the rest
        k_space_new[0:mm[0], 0:mm[1], 0:mm[2]] = k_space_ref[0:mm[0], 0:mm[1], 0:mm[2]]

        # Reconstruct the image from the modified k-space
        img_reconstructed.append(run_ifft(k_space_new))

        if test:
            plt.figure()
            plt.imshow(np.abs(np.abs(img_reconstructed[-1][n_sl // 2, :, :]) - np.abs(img_reconstructed[-2][n_sl // 2, :, :])),
                       vmin=0, vmax=1e-5)
            plt.title(f"Iteration {num_iterations+1}")

        # Compute correlation between consecutive reconstructed images
        correlation = np.corrcoef(np.abs(img_reconstructed[-2].flatten()), np.abs(img_reconstructed[-1].flatten()))[0, 1]

        # Display correlation and current iteration number
        print("Iteration: %i, Convergence: %0.2e" % (num_iterations, (1 - correlation)))

        # Check if correlation reaches the desired threshold
        if (1-correlation) <= threshold or num_iterations >= 100:
            break

        # Increment the iteration counter
        num_iterations += 1

    if test:
        plt.figure()
        plt.imshow(np.abs(img_reconstructed[-1][n_sl // 2, :, :]), cmap='gray')
        plt.title(f"POCS")
        plt.show()


        # Get correlation with reference image
        correlation_1 = np.corrcoef(np.abs(img_ref.flatten()), np.abs(img_reconstructed[-1].flatten()))[0, 1]
        print("POCS compared to reference image:")
        print("Convergence: %0.2e" % (1 - correlation_1))

    return k_space_new

def run_zero_padding_reconstruction(n_points, factors, k_space_ref):
    """
    Run the partial reconstruction operation.

    Retrieves the necessary parameters and performs the partial reconstruction on the loaded image.
    Updates the main matrix of the image view widget with the partially reconstructed image, adds the operation to
    the history widget, and updates the operations history.
    """
    # Get the k_space data and its shape
    img_ref = run_ifft(k_space_ref)

    # Percentage for partial reconstruction from the text field
    factors = [float(num) for num in factors][-1::-1]
    mm = np.array([int(num) for num in (n_points * factors)])

    # Set to zero the corresponding values
    k_space = np.zeros_like(k_space_ref, dtype=complex)
    k_space[:mm[0], :mm[1], :mm[2]] = k_space_ref[:mm[0], :mm[1], :mm[2]]

    # Calculate logarithmic scale
    image = run_ifft(k_space)

    # Get correlation with reference image
    correlation = np.corrcoef(np.abs(img_ref.flatten()), np.abs(image.flatten()))[0, 1]
    print("ZP compared to reference image:")
    print("Convergence: %0.2e" % (1 - correlation))

    return np.abs(image)

def fix_echo_position(data_oversampled, dummy_pulses, etl, n_rd, n_batches, n_readouts, n_scans, add_rd_points, oversampling_factor):
    """
    Adjust the position of k=0 in the echo data to the center of the acquisition window.

    This method uses oversampled data obtained with a given echo train length and readout gradient to determine the
    true position of k=0. It then shifts the sampled data to place k=0 at the center of each acquisition window for
    each gradient-spin-echo.

    Args:
        data_oversampled (numpy.ndarray): The original data array to be adjusted with dimensions [channels, etl, n].

    Returns:
        numpy.ndarray: The adjusted data array with k=0 positioned at the center of each acquisition window.

    """
    # Get relevant data
    data_noise = []
    data_dummy = []
    data_signal = []
    points_per_rd = n_rd * oversampling_factor
    points_per_train = points_per_rd * etl
    idx_0 = 0
    idx_1 = 0
    for batch in range(n_batches):
        n_rds = n_readouts[batch] * oversampling_factor
        for scan in range(n_scans):
            idx_1 += n_rds
            data_prov = data_oversampled[idx_0:idx_1]
            data_noise = np.concatenate((data_noise, data_prov[0:points_per_rd]), axis=0)
            if dummy_pulses > 0:
                data_dummy = np.concatenate((data_dummy, data_prov[points_per_rd:points_per_rd + points_per_train]),
                                            axis=0)
            data_signal = np.concatenate((data_signal, data_prov[points_per_rd + points_per_train::]), axis=0)
            idx_0 = idx_1

    # Get echo position
    data_dummy_b = np.reshape(data_dummy, (-1, etl, points_per_rd))
    data_dummy_b = np.average(data_dummy_b, axis=0)
    idx = np.argmax(np.abs(data_dummy_b[:, 5:-5]), axis=1) + 5

    # Apply to full data
    data_signal = []
    idx_0 = 0
    idx_1 = 0
    for batch in range(n_batches):
        n_rds = n_readouts[batch] * oversampling_factor
        for scan in range(n_scans):
            idx_1 += n_rds
            data_prov = data_oversampled[idx_0:idx_1]
            if dummy_pulses > 0:
                data_dummy = data_prov[points_per_rd:points_per_rd + points_per_train]
                data_dummy = np.reshape(data_dummy, (etl, points_per_rd))
                data_signal = data_prov[points_per_rd + points_per_train::]
                data_signal = np.reshape(data_signal, (-1, etl, points_per_rd))
                for ii in range(etl):
                    dx = 0
                    if idx[ii] >= points_per_rd // 2:
                        dx = points_per_rd - idx[ii]
                    if idx[ii] < points_per_rd // 2:
                        dx = idx[ii]
                    data_dummy[ii, points_per_rd // 2 - dx:points_per_rd // 2 + dx] = data_dummy[ii, idx[ii] - dx: idx[ii] + dx]
                    data_signal[:, ii, points_per_rd // 2 - dx:points_per_rd // 2 + dx] = data_signal[:, ii, idx[ii] - dx: idx[ii] + dx]
                data_dummy = np.reshape(data_dummy, -1)
                data_signal = np.reshape(data_signal, -1)
                data_prov[points_per_rd:points_per_rd + points_per_train] = data_dummy
                data_prov[points_per_rd + points_per_train::] = data_signal
            data_oversampled[idx_0:idx_1] = data_prov
            idx_0 = idx_1

    # Decimate the signal
    data_decimated = decimate(data_over=data_oversampled,
                              n_adc=np.size(data_oversampled)//points_per_rd,
                              option='Normal',
                              remove=False,
                              add_rd_points=add_rd_points,
                              oversampling_factor=oversampling_factor)

    return data_decimated

def decimate(data_over, n_adc, option='PETRA', remove=True, add_rd_points=10, oversampling_factor=5, decimation_factor=5):
    """
    Decimate oversampled MRI readout data using a two-stage approach:
    FIR decimation followed by optional frequency-domain downsampling.

    This function converts oversampled ADC data to the desired bandwidth.
    First, an FIR anti-aliasing decimation is applied. If the acquisition
    oversampling factor is larger than the FIR decimation factor, the
    remaining reduction is performed by frequency-domain cropping
    (equivalent to ideal low-pass filtering and resampling).

    Parameters
    ----------
    data_over : numpy.ndarray
        Oversampled ADC data as a 1D array. Length must be divisible by
        `n_adc`. Typically complex-valued MRI readout data.
    n_adc : int
        Number of ADC windows (readout lines). Used to reshape the data
        into (n_adc, samples_per_line) for per-line processing.
    option : {'PETRA', 'Normal'}, optional
        Preprocessing mode applied before decimation:
        - 'PETRA': Flattens the first `add_rd_points * oversampling_factor`
          samples of each readout line to suppress FIR edge oscillations.
        - 'Normal': No preprocessing.
        Default is 'PETRA'.
    remove : bool, optional
        If True, removes `add_rd_points` samples from the beginning and end
        of each readout line after decimation. Default is True.
    add_rd_points : int, optional
        Number of additional readout points acquired at both ends of each
        line. Default is 10.
    oversampling_factor : int, optional
        Oversampling factor used during acquisition. Defines the total
        effective decimation applied. Default is 5.
    decimation_factor : int, optional
        FIR decimation factor applied with anti-alias filtering. Must divide
        `oversampling_factor`. Any remaining factor is applied by
        frequency-domain downsampling. Default is 5.

    Returns
    -------
    numpy.ndarray
        Decimated data as a flattened 1D array.

    Raises
    ------
    ValueError
        If `oversampling_factor` is not a multiple of `decimation_factor`.

    Notes
    -----
    - Total effective decimation equals `oversampling_factor`.
    - FIR decimation uses `scipy.signal.decimate` with an FIR filter and
      zero-phase compensation.
    - A half-filter-length sample offset is applied before FIR decimation
      to align output samples.
    - When additional downsampling is required, each ADC window is
      transformed to k-space, center-cropped, and transformed back.
    - PETRA preprocessing reduces Gibbs-like ringing caused by FIR filtering
      near the start of each readout line.

    Workflow
    --------
    1. Reshape into ADC windows.
    2. Optionally apply PETRA edge stabilization.
    3. Apply FIR decimation.
    4. Apply frequency-domain downsampling if required.
    5. Optionally remove extra readout points per line.
    """

    # Get averaging factor
    if oversampling_factor % decimation_factor != 0:
        raise ValueError("oversampling_factor must be a multiple of decimation_factor")
    avg_factor = oversampling_factor // decimation_factor

    # Preprocess the signal to avoid oscillations due to decimation
    if option == 'PETRA':
        data_over = np.reshape(data_over, (n_adc, -1))
        for line in range(n_adc):
            data_over[line, 0:add_rd_points * oversampling_factor] = data_over[
                line, add_rd_points * oversampling_factor]
        data_over = np.reshape(data_over, -1)
    elif option == 'Normal':
        pass

    # Decimate the signal after 'fir' filter
    if decimation_factor > 1:
        data_decimated = sp.signal.decimate(data_over[int((decimation_factor - 1) / 2)::],
                                            decimation_factor,
                                            ftype='fir',
                                            zero_phase=True)
    else:
        data_decimated = data_over

    # Remaining decimation by averaging
    if avg_factor > 1:
        data_decimated = data_decimated.reshape(n_adc, -1)
        n = (data_decimated.shape[1] // avg_factor) * avg_factor
        data_decimated = data_decimated[:, :n]

        # FFT Method
        data_decimated = np.fft.fftshift(np.fft.ifft(np.fft.ifftshift(data_decimated, axes=1), axis=1), axes=1)
        nr_in = np.size(data_decimated, 1)
        nr_out = nr_in // avg_factor
        n0 = nr_in // 2 - nr_out // 2
        n1 = nr_in // 2 + nr_out // 2
        data_decimated = data_decimated[:, n0:n1]
        data_decimated = np.fft.ifftshift(np.fft.fft(np.fft.fftshift(data_decimated, axes=1), axis=1), axes=1)

        # # AVG Method
        # data_decimated = data_decimated.reshape(n_adc, -1, avg_factor).mean(axis=2)

        # Reshape the output
        data_decimated = data_decimated.reshape(-1)

    # Remove add_rd_points
    if remove:
        nPoints = int(data_decimated.shape[0] / n_adc) - 2 * add_rd_points
        data_decimated = np.reshape(data_decimated, (n_adc, -1))
        data_decimated = data_decimated[:, add_rd_points:add_rd_points + nPoints]
        data_decimated = np.reshape(data_decimated, -1)

    return data_decimated

def get_snr_histogram(image, roi_size=4):
    """
    Compute a pixel-wise SNR map for a 3D image.
    1) signal: mean value in a cubic ROI.
    2) noise: mean noise from the histogram.
    SNR = local signal / noise from the histogram.

    Parameters
    ----------
    image : np.ndarray
        3D image (e.g., shape (x, y, z)).
    roi_size : int
        Size of the cubic ROI (odd number recommended, e.g., 3, 5, 7).

    Returns
    -------
    snr_map : np.ndarray
        3D array with same shape as `image`, containing SNR values.
    """

    image = np.abs(image)
    image = image.astype(np.float64)

    # Local mean
    mean = sp.ndimage.uniform_filter(image, roi_size)

    # Get histogram
    counts, bins = np.histogram(mean, bins=512)

    # Find the peak (maximum count)
    peak_bin_index = np.argmax(counts)
    peak_value = (bins[peak_bin_index] + bins[peak_bin_index + 1]) / 2

    # Get SNR
    snr = mean / peak_value
    return snr

def get_snr_3d(image, roi_size=4):
    """
    Compute a pixel-wise SNR map for a 3D image.
    SNR = local mean / local std, computed in a cubic ROI.

    Parameters
    ----------
    image : np.ndarray
        3D image (e.g., shape (x, y, z)).
    roi_size : int
        Size of the cubic ROI (odd number recommended, e.g., 3, 5, 7).

    Returns
    -------
    snr_map : np.ndarray
        3D array with same shape as `image`, containing SNR values.
    """

    image = np.abs(image)
    image = image.astype(np.float64)
    # Local mean
    mean = sp.ndimage.uniform_filter(image, roi_size)
    # Local variance and std
    var = sp.ndimage.uniform_filter((image - mean) ** 2, roi_size)
    std = np.sqrt(var)
    # Avoid division by zero
    snr = mean / std
    return snr

def get_snr_2d(image, roi_size=4):
    """
    Compute a pixel-wise SNR map for a 3D image slice by slice.
    SNR = local mean / local std, computed in a cubic ROI.

    Parameters
    ----------
    image : np.ndarray
        3D image (e.g., shape (x, y, z)).
    roi_size : int
        Size of the cubic ROI (odd number recommended, e.g., 3, 5, 7).

    Returns
    -------
    snr_map : np.ndarray
        3D array with same shape as `image`, containing SNR values.
    """

    n_sl, n_ph, n_rd = image.shape
    snr = np.zeros((n_sl, n_ph, n_rd))
    for sl in range(n_sl):
        image_sl = np.abs(image[sl])
        image_sl = image_sl.astype(np.float64)
        # Local mean
        mean = sp.ndimage.uniform_filter(image_sl, roi_size)
        # Local variance and std
        var = sp.ndimage.uniform_filter((image_sl - mean) ** 2, roi_size)
        std = np.sqrt(var)
        # Avoid division by zero
        snr[sl] = mean / std
    return snr

def get_snr_from_individual_acquisitions(data, roi_size):
    """
    Compute a voxel-wise SNR map from a 4D dataset composed of repeated acquisitions.

    The function treats the first dimension of `data` as the acquisition axis:
    - The **signal** is computed as the mean magnitude across acquisitions,
      followed by a uniform (mean) filter of size `roi_size`.
    - The **noise** is computed as the standard deviation of the magnitude across
      acquisitions, also followed by the same uniform filter.

    Parameters
    ----------
    data : np.ndarray
        4D array (n_acq, x, y, z) containing repeated measurements of the same volume.
    roi_size : int
        Size of the cubic window for the uniform filter. An odd value (e.g., 3, 5, 7)
        is recommended to maintain symmetry.

    Returns
    -------
    snr_map : np.ndarray
        3D array with shape (x, y, z), containing the computed SNR values.
    """

    noise = np.std(np.abs(data), axis=0)
    mean = np.mean(np.abs(data), axis=0)
    noise = sp.ndimage.uniform_filter(noise, roi_size)
    signal = sp.ndimage.uniform_filter(mean, roi_size)
    snr = signal / noise
    return snr


if __name__ == "__main__":
    pass
    # from matplotlib import pyplot as plt
    mat_data = sp.io.loadmat("RarePyPulseq_T1_COR.mat")
    image = mat_data['image3D_den'][:, ::-1, :]
    axes = mat_data['axesOrientation'].squeeze()
    n_points = mat_data['nPoints'].squeeze()
    fov = mat_data['fov'].squeeze()
    dfov = mat_data['dfov'].squeeze()
    session = {
        "study": "wrist",
        "side": "Left",
        "orientation": "FFS",
    }
    save_dicom(axes, n_points, fov, dfov, image, "FFS.dcm", session = session)
    x = 0
